import requests
import re
import json
import time

# API endpoint and file paths
url = "https://bitnodes.io/api/v1/snapshots/latest/"
previous_file = "knownknots.txt"
banlist_file = "banlist.json"

# Timestamps
ban_created = int(time.time())
banned_until = int(time.time()) + (100 * 365 * 24 * 60 * 60)  # 100 years

def strip_port(address):
    # Remove port from IPv4, IPv6, and onion addresses
    if address.startswith('['):
        # IPv6 with brackets: [2001:db8::1]:8333
        return re.sub(r'^\[(.*)\]:\d+$', r'\1', address)
    else:
        # IPv4 or onion
        return address.split(':')[0]

def get_address_type(address):
    # Categorize address by type
    if re.match(r'^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$', address):
        return 'IPv4'
    elif re.match(r'^[0-9a-fA-F:]+$', address):
        return 'IPv6'
    elif address.endswith('.onion'):
        return 'onion'
    return 'unknown'

# Fetch data from API
try:
    response = requests.get(url)
    response.raise_for_status()
    data = response.json()
except requests.RequestException as e:
    print(f"Failed to fetch data from API: {e}")
    exit(1)

# Extract nodes
nodes = data.get("nodes", {})

# Get current Knots addresses (clean, no port)
current_addresses = set()
for address, details in nodes.items():
    if len(details) > 1:
        user_agent = details[1]
        if "Knots" in user_agent:
            clean_address = strip_port(address)
            current_addresses.add(clean_address)

# Read previous addresses
previous_addresses = set()
try:
    with open(previous_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Ignore anything after # (old user agent comments)
            addr = line.split('#', 1)[0].strip()
            previous_addresses.add(addr)
except FileNotFoundError:
    print(f"Previous file {previous_file} not found. Starting fresh.")

# Combine current + historical
all_addresses = previous_addresses | current_addresses

# New addresses this run
new_addresses = current_addresses - previous_addresses

# Categorize addresses
ipv4_addresses = [a for a in all_addresses if get_address_type(a) == 'IPv4']
ipv6_addresses = [a for a in all_addresses if get_address_type(a) == 'IPv6']
onion_addresses = [a for a in all_addresses if get_address_type(a) == 'onion']
unknown_addresses = [a for a in all_addresses if get_address_type(a) == 'unknown']

# Create banlist entries
banlist = []
for address in ipv4_addresses + ipv6_addresses + onion_addresses + unknown_addresses:
    addr_type = get_address_type(address)
    if addr_type == 'IPv4':
        formatted_address = f"{address}/32"
    elif addr_type == 'IPv6':
        formatted_address = f"{address}/128"
    else:  # onion or unknown
        formatted_address = address

    entry = {
        "version": 1,
        "ban_created": ban_created,
        "banned_until": banned_until,
        "address": formatted_address
    }
    banlist.append(entry)

# Bitcoin Core banlist structure
output_data = {
    "_warning_": "This file is automatically generated and updated by Bitcoin Core. Please do not edit this file while the node is running, as any changes might be ignored or overwritten.",
    "banned_nets": banlist
}

# Write banlist.json
with open(banlist_file, "w", encoding="utf-8") as f:
    json.dump(output_data, f, indent=4)

# Write knownknots.txt — only clean addresses, one per line, sorted
with open(previous_file, "w", encoding="utf-8") as f:
    all_sorted = sorted(ipv4_addresses) + sorted(ipv6_addresses) + sorted(onion_addresses) + sorted(unknown_addresses)
    for address in all_sorted:
        f.write(f"{address}\n")

# Print summary
print(f"Banlist written to {banlist_file}")
print(f"Updated known knots list in {previous_file} (addresses only)")
print(f"Total unique Knots addresses: {len(all_addresses)}")
print(f"  - IPv4: {len(ipv4_addresses)}")
print(f"  - IPv6: {len(ipv6_addresses)}")
print(f"  - Onion: {len(onion_addresses)}")
print(f"New Knots addresses added this run: {len(new_addresses)}")